#
# Compose file for the DTVF (Development).
#
version: "3.8"

# All Services
services:

  # Compilation container.
  # This container will compile the source code, package it for deployment, write it to the ./output folder, then shutdown.
  compile:
    build:
      context: "../"
      dockerfile: "./build.Dockerfile"
    image: ghcr.io/cambridge-cares/dtvf-build-environment:latest
    container_name: "dtvf-build-compile"
    restart: "no"
    working_dir: "/app"
    entrypoint: "/bin/bash -c 'npm install && tsc && grunt package'"
    volumes:
      - type: bind
        source: ../
        target: /app