# This file is provided in order to upload an image to the github Docker registry

version: '3.8'
services:
  propertyvalue_agent_deriv_mvp:
    image: ghcr.io/cambridge-cares/propertyvalue_agent_deriv_mvp:1.0.0-SNAPSHOT
    container_name: propertyvalue_agent_deriv_mvp
    environment:
      LOG4J_FORMAT_MSG_NO_LOOKUPS: "true"
    build:
      context: .
      target: derivation_mvp
      args:
        # Build argument used to construct paths in Dockerfile (needs to match name in setup.py)
        agentdir: propertyvalueestimation
