# This configuration file should include any docker-compose options used only when deploying the
# stack WITH the '--test' flag.
# Its counterpart is docker-compose.live.yml.
#
# The expectation is that this file will contain 'ports' nodes for any services that need to map a
# host port, but other options may be valid too - please consult CMCL admins for more details.
# For guidance in setting an appropriate port number, please see the instructions at
# https://github.com/cambridge-cares/TheWorldAvatar/wiki/Docker:-Stacks#instructions-1
# =================================================================================================

version: "3.8"


services:

  # Email Agent
  email-agent:
    ports:
      - 49080:8080

  # Gas Grid Agent
  gas-grid-agent:
    ports:
      - 41081:80

  # Flood Agent
  flood-agent:
    ports:
      - 41082:80
      
  # JPS Chatbot
  jps-chatbot:
    ports:
      - 46000:5000

  # JPS LDF Server
  jps-ldf:
    ports:
      - 44000:3000

  # # Kinetics Agent
  # kinetics-agent:
  #   ports:
  #     - 49081:8080

  # OSCML Agent
  oscml-agent:
    ports:
      - 46001:5000