# This configuration file should include any docker-compose options used only when deploying the
# stack WITHOUT the '--test' flag (i.e. in normal running).
# Its counterpart is docker-compose.test.yml.
#
# The expectation is that this file will contain 'ports' nodes for any services that need to map a
# host port, but other options may be valid too - please consult CMCL admins for more details.
# For guidance in setting an appropriate port number, please see the instructions at
# https://github.com/cambridge-cares/TheWorldAvatar/wiki/Docker:-Stacks#instructions-1
# =================================================================================================

version: "3.8"


services:

  # Flood Map
  flood-map:
    ports:
      - 40085:80

  # Land Use Crop Map
  land-use:
    ports:
      - 40082:80

 # Reverse Proxy
  reverse-proxy:
    ports:
      - 80:80
      - 443:443

  # Gas Grid Visualisation
  uk-gas-grid:
    ports:
      - 40084:80

  # Power System and SDG Visualisation
  uk-power-system:
    ports:
      - 40083:80