version: "3.8"

# All Services
services:

  # Example DTVF implementation
  ntu-cesium-vis:
    image: ghcr.io/cambridge-cares/dtvf-base-image:latest
    container_name: "ntu-cesium-vis"
    ports:
      - "80:80"
    volumes:
      - ./webspace:/var/www/html
 