version: '3.8'
services:
  stack-data-uploader:
    image: ghcr.io/cambridge-cares/stack-data-uploader${IMAGE_SUFFIX}:1.20.3
    secrets:
      - blazegraph_password
      - postgis_password
      - geoserver_password
    volumes:
      - ./data:/inputs/data:z
      - ./config:/inputs/config
