version: '3.8'

services:
  resultedconsumptionagent:
    build:
      context: .
      target: prod
      args:
        # Build argument used to construct paths in Dockerfile (needs to match name in setup.py)
        agentdir: resultedconsumptionagent
