version: "3.8"

services:
  epc_agent:
    image: ghcr.io/cambridge-cares/epc_agent:1.0.0
    environment:
      - STACK_NAME=${STACK_NAME}
      # Base64-encoded authentication token for EPC API (identifier composed of your email address and api-key)
      # Obtained from https://epc.opendatacommunities.org/docs/api/domestic when signed in 
      - ENCODED_AUTH=
      # Table name in PostGIS, also Layer name in Geoserver
      - LAYERNAME=buildings
      # Target Blazegraph namespace
      - NAMESPACE=buildings
      # Specify PostGIS/PostgreSQL database name
      # (default name "postgres" required for Ontop to work)
      - DATABASE=postgres
      - GEOSERVER_WORKSPACE=buildings
      - ONTOP_FILE=/app/resources/ontop.obda
      - OCGML_ENDPOINT=
    ports:
      - "5001:5000"
    volumes:
      # Link container output directory to local directory to access output files
      - ./data:/app/data
      - logs:/root/.jps
    configs:
      - blazegraph
      - geoserver
      - ontop
      - postgis
    secrets:
      - geoserver_password
      - postgis_password

volumes:
  logs:
    name: "logs"
