version: "3.8"

services:
  epc_agent:
    image: ghcr.io/cambridge-cares/epc_agent:1.0.0-SNAPSHOT
    environment:
      - STACK_NAME=${STACK_NAME}
      # Authentication token for EPC API
      - API_AUTH=
      # Layer name in geoserver, also table name in PostGIS
      - LAYERNAME=buildings
      # Target Blazegraph namespace
      - NAMESPACE=buildings
      # Specify PostGIS/PostgreSQL database name
      # (default name "postgres" required for Ontop to work)
      - DATABASE=postgres
      - GEOSERVER_WORKSPACE=buildings
      - ONTOP_FILE=/app/resources/ontop.obda
      - OCGML_ENDPOINT=
    ports:
      - "5001:5000"
    volumes:
      # Link container output directory to local directory to access output files
      - ./data:/app/data
      - logs:/root/.jps
    configs:
      - blazegraph
      - geoserver
      - ontop
      - postgis
    secrets:
      - geoserver_password
      - postgis_password

volumes:
  logs:
    name: "logs"
