version: "3.8"

# All Services
services:

  # Example DT Visualisation
  example-dt-vis:
    image: docker.cmclinnovations.com/example-dtvf:1.0.0-SNAPSHOT
    container_name: example-dtvf
    build: 
      context: "../"
      dockerfile: "./docker/Dockerfile"
      target: "dev"
      labels:
        authors: "support@cmclinnovations"
        description: "Example implementation of the Digital Twin Visualisation Framework."
    ports:
      - "65080:80"
 