version: '3.8'

services:
  api_agent:
    image: ghcr.io/cambridge-cares/api_agent:1.0.0-SNAPSHOT
    container_name: api_agent
    environment:
      LOG4J_FORMAT_MSG_NO_LOOKUPS: "true"
    build:
      context: .
      target: prod
    ports:
      - 7000:5000
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - ./agent.env.test
    volumes:
      # To run docker inside docker, mount default Unix socket docker.sock as a volume
      # (https://devopscube.com/run-docker-in-docker/)
      - /var/run/docker.sock:/var/run/docker.sock