version: "3.8"

services:

  # Feature Info Agent
  feature-info-agent:
    image: ghcr.io/cambridge-cares/feature-info-agent:2.0.0
    build: .
    environment:
      LOG4J_FORMAT_MSG_NO_LOOKUPS: "true"
      FIA_CONFIG_FILE: "/app/queries/fia-config.json"
    configs:
      - blazegraph
      - ontop
      - postgis
    secrets:
      - postgis_password
    volumes:
      - ./queries:/app/queries