version: "3.8"

services:
  trajectoryqueryagent:
    image: ghcr.io/cambridge-cares/trajectoryqueryagent:1.0.0
    build: .
    ports:
      - "10108:8080"
    volumes:
      - ./trajectoryqueryagent/src/main/resources:/resources