# This configuration file should include all docker-compose options required to *build images* for
# services in the 'db' stack.
#
# When adding a new service, please copy the configuration for an existing service, then modify the
# service name, the 'image' tag (retaining 'docker.cmclinnovations.com') and the 'build/*',
# 'labels/authors' and 'labels/description' nodes.
# =================================================================================================

version: "3.8"


services:

  # Blazegraph
  blazegraph:
    image: docker.cmclinnovations.com/blazegraph:1.0.0-SNAPSHOT
    build:
      context: blazegraph
      labels:
        authors: "support@cmclinnovations"
        builder: "${BUILDER}"
        description: "Blazegraph with BASIC authentication, based on the official Tomcat 9 image."
        hash: "${HASH}"

  # Blazegraph geo
  blazegraph-geo:
    image: docker.cmclinnovations.com/blazegraph_geo:1.0.0-SNAPSHOT
    build:
      context: blazegraph_geo
      labels:
        authors: "msff2@cam.ac.uk, support@cmclinnovations"
        builder: "${BUILDER}"
        description: "Customised version of Blazegraph, optimised for particular geospatial queries. Based on the official Tomcat 9 image."
        hash: "${HASH}"

  # File server
  fileserver:
    image: docker.cmclinnovations.com/fileserver:1.0.0-SNAPSHOT
    build:
      args:
        mvn_profile: ${MODE}-profile
      context: fileserver
      labels:
        authors: "support@cmclinnovations"
        builder: "${BUILDER}"
        description: "Tomcat servlet designed to simplify the storage and retrieval of files referenced in the knowledge graph."
        hash: "${HASH}"

  # RDF4J
  rdf4j:
    image: docker.cmclinnovations.com/rdf4j:1.0.0-SNAPSHOT
    build:
      context: rdf4j
      labels:
        authors: "support@cmclinnovations"
        builder: "${BUILDER}"
        description: "RDF4J with BASIC authentication for the server and workbench."
        hash: "${HASH}"