version: "3.8"

services:
  forecasting_agent:
    image: ghcr.io/cambridge-cares/forecasting_agent:1.1.0
    environment:
      # Required environment variables for both Stack and "standalone" (i.e. outside stack) deployment
      - STACK_NAME=TEST         # to be left blank for "standalone" deployment
      # Additional environment variables required for Stack deployment
      # (can be left blank for "standalone" deployment)
      - NAMESPACE=test          # Target Blazegraph namespace
      - DATABASE=test           # Target PostGIS/PostgreSQL database name
      # Additional environment variables required for "standalone deployment"
      # (can be left blank for Stack deployment)
      - DB_URL=
      - DB_USER=
      - DB_PASSWORD=
      - QUERY_ENDPOINT=
      - UPDATE_ENDPOINT=
    build:
      # Path to dockerfile ('.' represents current directory with .yml file)
      context: .
      target: prod
    ports:
      - "5005:5000"
    volumes:
      - logs:/root/.jps

volumes:
  logs:
    name: "logs"