#
# Compose file for the TWA-VP.
#
services:

  # Builds a base image that, when combined with a volume of files, can be used as a visualisation for development purposes. 
  # It is not intended that this config is used to run the production image.
  visualise:
    image: ghcr.io/cambridge-cares/dev-twa-vf:latest-SNAPSHOT
    container_name: "dev-twa-vf"
    restart: "no"
    environment:
      WATCHPACK_POLLING: true
      UUID: 1000 # or your user. Run `id` in bash to find out these two
      GUID: 1000 # or your guid. This is so you own node modules that the container makes on your host machine
    secrets:
      - mapbox_username
      - mapbox_api_key
    build:
      context: "./"
      dockerfile: "Dockerfile"
      target: develop
      labels:
        authors: "support@cmcl.io"
        description: "Development environment for TWA Visualisation Platform image."
    volumes:
      - ./code:/twa/
    ports:
      - "3000:3000" 
secrets:
    mapbox_username: 
      file: ./mapbox_username
    mapbox_api_key:
      file: ./mapbox_api_key
