version: "3.8"

services:
  Historical-NUSDavis-agent:
    image: historical-nusdavis-agent:1.0.0
    build: .
    container_name: Historical-NUSDavis-agent
    pull_policy: if_not_present
    ports:
      - "1026:8080"