version: "3.8"

services:
  floodwarnings_agent:
    image: ghcr.io/cambridge-cares/floodwarnings_agent:1.1.2
    environment:
      - STACK_NAME=${STACK_NAME}
      # Target Blazegraph namespace
      - NAMESPACE=kingslynn
      # Target PostGIS database name
      # (default name "postgres" required for Ontop to work)
      - DATABASE=postgres
      # Target table name in PostGIS (also layer name in Geoserver)
      - LAYERNAME=floodwarnings
      - GEOSERVER_WORKSPACE=kingslynn
      - ONTOP_FILE=/app/resources/ontop.obda
      # PostGIS table with building footprints
      - BUILDINGS_TABLE=buildings
      # Derivation Agent configuration
      # (value needs to match counterpart specified in the docker-compose.yml file of FloodAssessmentAgent)
      - FLOOD_ASSESSMENT_AGENT_IRI=https://www.theworldavatar.com/resource/agents/Service__KL_FloodAssessment/Service
    ports:
      - "5009:5000"
    volumes:
      - logs:/root/.jps
    configs:
      - blazegraph
      - geoserver
      - ontop
      - postgis
    secrets:
      - geoserver_password
      - postgis_password

volumes:
  logs:
    name: "logs"
