version: '3.8'
services:
  stack-data-uploader:
    secrets:
      - source: blazegraph
        target: /blazegraph
      - source: postgis 
        target: /postgis
      - source: geoserver 
        target: /geoserver

secrets:
  blazegraph:
    name: ${STACK_NAME}_blazegraph
    external: true
  postgis:
    name: ${STACK_NAME}_postgis
    external: true
  geoserver:
    name: ${STACK_NAME}_geoserver
    external: true
